<a href="https://colab.research.google.com/github/MiG27K/First/blob/main/Titled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

In [29]:
df = pd.read_csv('Expanded_data_with_more_features.csv')
df.drop(['Unnamed: 0'], axis=1)
df['EthnicGroup'].unique()
# df = df['EthnicGroup'].fillna('group C')
df[['EthnicGroup']] = df[['EthnicGroup']].fillna('group C')

df['ParentEduc'].unique()
df[['ParentEduc']] = df[['ParentEduc']].fillna('some college')

df['TestPrep'].unique()
df[['TestPrep']] = df[['TestPrep']].fillna('nan')

df['ParentMaritalStatus'].unique()
df[['ParentMaritalStatus']] = df[['ParentMaritalStatus']].fillna('married')

df['PracticeSport'].unique()
df[['PracticeSport']] = df[['PracticeSport']].fillna('sometimes')

df['IsFirstChild'].unique()
df[['IsFirstChild']] = df[['IsFirstChild']].fillna('yes')

df['NrSiblings'].unique()
df[['NrSiblings']] = df[['NrSiblings']].fillna(1.0)

df['TransportMeans'].unique()
df[['TransportMeans']] = df[['TransportMeans']].fillna('other')

df['WklyStudyHours'].unique()
df[['WklyStudyHours']] = df[['WklyStudyHours']].fillna('5  - 10')
df.isnull().sum()

Unnamed: 0             0
Gender                 0
EthnicGroup            0
ParentEduc             0
LunchType              0
TestPrep               0
ParentMaritalStatus    0
PracticeSport          0
IsFirstChild           0
NrSiblings             0
TransportMeans         0
WklyStudyHours         0
MathScore              0
ReadingScore           0
WritingScore           0
dtype: int64

In [44]:
label_encoder = LabelEncoder()
encoded_data = label_encoder.fit_transform(df['Gender'])
df['Gender'] = encoded_data

encoded_data = label_encoder.fit_transform(df['EthnicGroup'])
df['EthnicGroup'] = encoded_data

encoded_data = label_encoder.fit_transform(df['ParentEduc'])
df['ParentEduc'] = encoded_data

encoded_data = label_encoder.fit_transform(df['LunchType'])
df['LunchType'] = encoded_data

encoded_data = label_encoder.fit_transform(df['TestPrep'])
df['TestPrep'] = encoded_data

encoded_data = label_encoder.fit_transform(df['ParentMaritalStatus'])
df['ParentMaritalStatus'] = encoded_data

encoded_data = label_encoder.fit_transform(df['PracticeSport'])
df['PracticeSport'] = encoded_data

encoded_data = label_encoder.fit_transform(df['IsFirstChild'])
df['IsFirstChild'] = encoded_data

encoded_data = label_encoder.fit_transform(df['NrSiblings'])
df['NrSiblings'] = encoded_data

encoded_data = label_encoder.fit_transform(df['TransportMeans'])
df['TransportMeans'] = encoded_data

encoded_data = label_encoder.fit_transform(df['WklyStudyHours'])
df['WklyStudyHours'] = encoded_data

encoded_data = label_encoder.fit_transform(df['MathScore'])
df['MathScore'] = encoded_data

encoded_data = label_encoder.fit_transform(df['ReadingScore'])
df['ReadingScore'] = encoded_data

encoded_data = label_encoder.fit_transform(df['WritingScore'])
df['WritingScore'] = encoded_data

df

,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,2,1,1,2,1,1,1,3,2,2,65,60,66
1,0,2,4,1,1,1,2,1,0,0,1,63,79,80
2,0,1,3,1,2,2,2,1,4,2,2,81,82,83
3,1,0,0,0,2,1,0,0,1,0,1,39,45,34
4,1,2,4,1,2,1,2,1,0,2,1,70,67,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30636,0,3,2,1,2,2,2,0,2,2,1,53,50,57
30637,1,4,2,1,2,2,1,0,1,1,1,52,42,43
30638,0,2,2,0,0,1,2,0,1,1,1,55,59,59
30639,0,3,0,1,0,1,1,0,3,2,1,76,79,85
30640,1,1,4,1,2,1,0,0,1,2,1,58,49,50

In [47]:
X_head = ['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'TestPrep',
       'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours']
X = df[X_head]

X

,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours
0,0,2,1,1,2,1,1,1,3,2,2
1,0,2,4,1,1,1,2,1,0,0,1
2,0,1,3,1,2,2,2,1,4,2,2
3,1,0,0,0,2,1,0,0,1,0,1
4,1,2,4,1,2,1,2,1,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...
30636,0,3,2,1,2,2,2,0,2,2,1
30637,1,4,2,1,2,2,1,0,1,1,1
30638,0,2,2,0,0,1,2,0,1,1,1
30639,0,3,0,1,0,1,1,0,3,2,1
30640,1,1,4,1,2,1,0,0,1,2,1

In [ ]:
x = 0