<a href="https://colab.research.google.com/github/MiG27K/First/blob/main/Titled_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd


df = pd.read_csv('results.csv')
lst = ['Hindi', 'English', 'Science', 'Maths', 'History',
       'Geograpgy', 'Results']
df = df[lst]
df

     Hindi  English  Science  Maths  History  Geograpgy  Results
0       65       10       59      3       71         37        0
1       94       56        4     67       91         50        1
2        7       85       76     99       60         25        0
3       88       46       59     94       52         38        1
4       39       81       37     38        6         54        1
..     ...      ...      ...    ...      ...        ...      ...
995     55       89       68     58       13         13        0
996     42       62       25     87       51         68        1
997      9       83       70     14       11         78        0
998     23       82       31     42       84         52        0
999     75       78       68     33       79         91        1

[1000 rows x 7 columns]

In [17]:
X = df[lst[:-1]]
X #Ð±Ð°Ð»Ð»Ñ‹ Ð·Ð° Ð·Ð°Ð´Ð°Ð½Ð¸Ðµ

     Hindi  English  Science  Maths  History  Geograpgy
0       65       10       59      3       71         37
1       94       56        4     67       91         50
2        7       85       76     99       60         25
3       88       46       59     94       52         38
4       39       81       37     38        6         54
..     ...      ...      ...    ...      ...        ...
995     55       89       68     58       13         13
996     42       62       25     87       51         68
997      9       83       70     14       11         78
998     23       82       31     42       84         52
999     75       78       68     33       79         91

[1000 rows x 6 columns]

In [19]:
y = df['Results']
y

0      0
1      1
2      0
3      1
4      1
      ..
995    0
996    1
997    0
998    0
999    1
Name: Results, Length: 1000, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [41]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression().fit(X_train, y_train)

In [42]:
y_pred = clf.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0])

In [43]:
#accurace = TP + TN / TP + TN + FP + FN
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8

In [44]:
#presision = TP / TP + FP
from sklearn.metrics import precision_score
precision_score(y_test, y_pred)

0.6847826086956522

In [45]:
#recall = TP / TP + FN
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

0.6702127659574468

In [46]:
#F = 2 * presision + recall / presision + recall
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)

0.6774193548387096

In [50]:
marks = [[63, 72, 90, 52, 65, 42]]
df2 = pd.DataFrame(marks, columns=lst[:-1])

In [53]:
res = clf.predict(df2)

In [54]:
def mark_predict(hindi, english, science, maths, history, geography):
  marks = [[hindi, english, science, maths, history, geography]]
  df2 = pd.DataFrame(marks, columns=lst[:-1])
  result = clf.predict(df2)[0]
  return result

In [55]:
mark_predict(52, 63, 99, 58, 13, 73)

1